### ISSUE TITLE
LSposed app instantly crashes

### ISSUE THREAD

**Issue by enskye** [ProtonAOSP/android_art#1]
LSposed app insantly crashes after launching. it will launch for sometime after device reboot. force stopping app brings in issue again. attaching logs below:

[logs](https://www.toptal.com/developers/hastebin/gupanugebo.yaml)

**Comment by cyberboh** [comment]
@kdrag0n please merge this commit https://github.com/GrapheneOS/platform_art/commit/433aef188cea2349dcadfb43d420dfd21adb4659
to avoid LSposed crash!

**Comment by kdrag0n** [comment]
Added for 12.3.3, thanks.
